In [35]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할 때 사용하는 자료구조
# 0차원 텐서: 스칼라  25 - 단일 데이터
# 1차원 텐서(벡터): 리스트 형탤  [1,2,3,4]
# 2차원 텐서(행렬): 행과 열로 이루어진 데이터  표데이터, 흑백 이미지(가로픽셀 x 세로픽셀)
# 3차원 텐서: 컬러이미지  흑백이미지 + 채널정보(R G B)
# 고차원 텐서: 동영상(가로픽셀 x 세로픽셀 x 채널정보 x 이미지개수)

# 데이터의 표준 형식: 일관된 숫자 형식
# 효율적인 계산: GPU 지원 병렬 연산에 유리
# 딥러닝 프레임워크: 텐서플로, 파이토치

In [59]:
%pip install tqdm

  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [36]:
%pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [37]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4)
x

tensor([[0.9725, 1.2421, 1.4293, 0.5142],
        [0.7140, 1.1359, 1.0913, 0.7266],
        [1.3909, 0.8701, 0.9620, 1.0556]])

In [38]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.0073, 0.6622, 0.2030, 0.5735],
        [0.5680, 0.4523, 0.5440, 0.0972],
        [0.7364, 0.5471, 0.1410, 0.3727]])

In [39]:
# 0으로 탠서 초기화
x = torch.zeros(3,4,dtype=torch.long)
x

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [40]:
# 1로 텐서 초기화
x = torch.ones(3,4,dtype=torch.long)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [41]:
import numpy as np
print(torch.tensor( [3.5, 3, 2.1]))
print(np.array([3.5, 3, 2.1]))

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [42]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x, dtype=torch.float)

x,  y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[-1.0518, -0.2509,  1.2709,  0.0681],
         [ 0.6888,  0.0158,  0.6733,  1.2359],
         [ 1.2923,  0.2753,  0.7482, -0.6520]]))

In [43]:
import torch
x = torch.rand(3,4)
y = torch.rand(3,4)
x, y, x + y

(tensor([[0.4560, 0.8178, 0.4029, 0.7769],
         [0.4978, 0.1590, 0.9172, 0.3857],
         [0.7165, 0.1654, 0.3227, 0.0250]]),
 tensor([[0.3364, 0.8478, 0.4093, 0.0961],
         [0.3513, 0.8275, 0.0479, 0.7244],
         [0.1628, 0.7024, 0.0936, 0.5931]]),
 tensor([[0.7923, 1.6656, 0.8122, 0.8730],
         [0.8492, 0.9864, 0.9651, 1.1101],
         [0.8793, 0.8678, 0.4163, 0.6181]]))

In [44]:
torch.add(x,y)

tensor([[0.7923, 1.6656, 0.8122, 0.8730],
        [0.8492, 0.9864, 0.9651, 1.1101],
        [0.8793, 0.8678, 0.4163, 0.6181]])

In [45]:
# in-place y = y + x  y += x
y.add_(x)
y

tensor([[0.7923, 1.6656, 0.8122, 0.8730],
        [0.8492, 0.9864, 0.9651, 1.1101],
        [0.8793, 0.8678, 0.4163, 0.6181]])

In [46]:
# 행렬 곱셈
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y), x@y # 파이썬 3.5부터 @ 연산자 지원 x@y

(tensor([[0.7500, 0.7578, 0.7995, 0.5957],
         [0.2428, 0.8206, 0.7944, 0.5926],
         [0.7715, 0.5030, 0.1308, 0.6991]]),
 tensor([[0.6929, 0.5744, 0.8088, 0.3028, 0.7455],
         [0.1422, 0.3394, 0.5310, 0.1501, 0.5141],
         [0.7088, 0.3250, 0.3796, 0.5964, 0.0962],
         [0.6072, 0.5353, 0.3780, 0.1649, 0.8944]]),
 tensor([[1.5558, 1.2667, 1.5376, 0.9159, 1.5585],
         [1.2078, 0.9934, 1.1577, 0.7682, 1.2094],
         [1.1233, 1.0306, 1.2050, 0.5024, 1.4716]]),
 tensor([[1.5558, 1.2667, 1.5376, 0.9159, 1.5585],
         [1.2078, 0.9934, 1.1577, 0.7682, 1.2094],
         [1.1233, 1.0306, 1.2050, 0.5024, 1.4716]]))

In [47]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item())

(tensor(0.2578), 0.25779038667678833, torch.Tensor, float)

In [48]:
# 텐서 크기 변경 reshape, view | numpy의 reshape과 동일
x = torch.rand(4,4)
y = x.view(-1) # 1차원 텐서로 변경 | `-1`은 자동으로 크기 계산
x, y, x.shape, y.shape

(tensor([[0.4532, 0.8813, 0.7045, 0.5365],
         [0.2977, 0.2831, 0.2278, 0.0838],
         [0.9672, 0.2666, 0.6246, 0.2214],
         [0.8099, 0.2306, 0.3959, 0.3169]]),
 tensor([0.4532, 0.8813, 0.7045, 0.5365, 0.2977, 0.2831, 0.2278, 0.0838, 0.9672,
         0.2666, 0.6246, 0.2214, 0.8099, 0.2306, 0.3959, 0.3169]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [49]:
# x  4 by 4
# view : numpy의 reshape와 동일 | 텐서 모양 변경
# size : numpy의 shape와 동일 |  텐서 모양 확인
# 가독성....view size 사용되었다는 것은 해당 자료구조가 텐서라는 것을 명시
x.view(-1, 8), x.size() # 

(tensor([[0.4532, 0.8813, 0.7045, 0.5365, 0.2977, 0.2831, 0.2278, 0.0838],
         [0.9672, 0.2666, 0.6246, 0.2214, 0.8099, 0.2306, 0.3959, 0.3169]]),
 torch.Size([4, 4]))

In [50]:
# 텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [51]:
# 넘파이 -> 텐서
import torch
import numpy as np
a = np.array([1,2,3,4,5])
torch.from_numpy(a)

tensor([1, 2, 3, 4, 5])

In [52]:
torch.cuda.is_available()

False

In [53]:
# GPU 사용
import torch
if torch.cuda.is_available():
    device = torch.device('cuda') # GPU
    # 텐서들은 gpu에서 연산해야되기 때문에 생성을 gpu에서 생성
    x = torch.ones(5, device=device) # GPU에 텐서 생성
    y = torch.ones(5) # CPU에 텐서 생성
    y = y.to(device) # CPU -> GPU 이동
    z = x + y
    print(f"GPU 연산 결과: {z}")
    print(f"다시 CPU로 : {z.to('cpu', torch.double)}")
else:
    print("cuda 사용 불가")
    device = torch.device('cpu')

cuda 사용 불가


In [54]:
# 행렬의 곱
# (x,y) * (x1, y1)
# y , x1의 차수는 같아야 한다.
# 행렬곱의 결과는 x, y1

# 텐서는 딥러닝을 위해 만들 자료구조... 내부에 gpu 연산에 특화된 구조 일반적인 모양은 넘파이와 동일
# 텐서는 gpu 연산을 지원

In [55]:
# 자동 미분(AutoGrad) 매 계산과정마다 행당 계산과정의 미분값을 저장
# 파이토치 required_grad = True로 설정하면계산그래프라는 형태로 기록 - 동영상 녹화와 비슷한 원리
# .backword() 호출하면 이 과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다.

In [56]:
x = torch.ones(2,2, requires_grad=True)
x, x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [57]:
y = x + 2   # y도 계산 그래프에 추가
print(y, y.grad_fn)
z = y*y*3
out = z.mean()
z, out

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x000002C59A59B910>


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [ ]:
# 기울기 구하는 과정을 역전파 --> 기울기를 계산
# 최종결과가 out에서부터 시작해서 계산 그래프를 거꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 xp 대해서 미분
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [61]:
# out = 1/4 * (z1 + z2 + z3 + z4)
# z = 3 * y^2
# y = x + 2

# d-out/d-xi = 

In [83]:
# 기울기 제어
# 역전파, torch.no_gred(), detach
# required_grad = True 연산 추적
import torch
x = torch.randn(3, requires_grad=True)
print(x)
# y는 x로부터 연산기록을 물려받음
y = x * 2
# 노름(유클리드 노름) 벡터의 크기를 측정하는 방법(원점으로부터 벡터까지의 거리)  모든 요소를 각각 제곱하고 모두 더해서 결과에 제곱근(루트)
# y의 실제 데이터의 크기를 확인해서 반복
i = 0
while y.data.norm() < 1000:
    y = y*2
    i += 1
print (f'y: {y}')
print(f'반복횟수: {i}')

# 벡터에 대한 역전파(야코비안 행렬)
# 벡터를 벡터로 미분하면 결과는 행렬인 야코비안 행렬
# pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 야코비안 - 벡터 곱을 계산해서 메모리를 절약
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v) # y를 x에 대해 미분한 야코비안 행렬과 입력으로 제공된 벡터 v를 곱하라는 의미
# vt•J = x.grad
print(f'x.grad: {x.grad}')

tensor([ 0.1731, -1.4559,  1.8271], requires_grad=True)
y: tensor([  88.6112, -745.4291,  935.4893], grad_fn=<MulBackward0>)
반복횟수: 8
x.grad: tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


```
스칼라 백워드  Scalar Backward: 역전파로 구하는 기울기가 하나일 때
out.backward()
최종 점수가 숫자 하나    ex) 수학 공부 1시간 했을 때 최종 점수에 몇점에 영향을 줬는지
최종 목표가 하나(스칼라)이기 때문에 각 원인(각 변수)의 기여도를 바로 계산

벡터 백워드 Vector Backwar: 기울기가 여러개 일 때 
y.backward(v)
과목별(국영수) 점수가 담긴 성적표(벡터)     공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매함 국어성적? 영어성적?
가중치 또는 중요도를 알려주는 벡터  v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인
```

In [85]:
# 각 학습을 진행하면서 도중에 모델의 성능 평가가 필요 - 기울 기 계산을 하면 안됨
with torch.no_grad():
    print(f'no_grad 내부: {(x**2).requires_grad}')

# .detach() 계산그래프 텐서를 분리
print(f'detach 전 {y.requires_grad}')
y = x.detach()
print(f'detach 후 {y.requires_grad}')

no_grad 내부: False
detach 전 True
detach 후 False
